name: Chat
on:
  repository_dispatch:
    types: [chat-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
      - name: Trigging chat back
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          issue-number: 1
          body: "Hello world"
