name: Chat
on:
  repository_dispatch:
    types: [chat-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
      - name: Set variabler for image, namespace og cluster
        shell: bash
        run: |
          echo "TAG=$(echo ARGUMENTS.arg1 | cut -c16-22)" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE_BASE: $ARGUMENTS.arg1" >> $GITHUB_ENV
          echo "CLUSTER=$ARGUMENTS.arg2" >> $GITHUB_ENV
          echo "NAMESPACE=$ARGUMENTS.arg3" >> $GITHUB_ENV
        env:
          ARGUMENTS: ${{ github.event.client_payload.slash_command.args }}

      - name: Trigging chat back
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          issue-number: 1
          body: "Hello world"

      - name: Using dispatch payload
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              body: "${{ env.CLUSTER }}, ${{ env.NAMESPACE }}, ${{ env.TAG }}, ${{ env.IMAGE }}"
            }