name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy step
        shell: bash
        run: |
          echo "Running first step of promote"

      - name: Setting variables for image, namespace and cluster
        shell: bash
        run: |
          echo "TAG=$(echo ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }} | cut -c16-22)" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE_BASE:${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}" >> $GITHUB_ENV
          echo "CLUSTER=${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}" >> $GITHUB_ENV
          echo "NAMESPACE=${{ github.event.client_payload.slash_command.args.unnamed.arg3 }}" >> $GITHUB_ENV

      - name: Using dispatch payload
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              body: "${{ env.CLUSTER }}, ${{ env.NAMESPACE }}, ${{ env.TAG }}, ${{ env.IMAGE }}"
            })

      - name: Using dispatch payload
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              body: 'promote til ${{ github.event.client_payload.slash_command.args.all }} utført'
            })

