name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy step
        shell: bash
        run: |
          echo "Running first step of promote"